In [16]:
import pandas as pd

conditions = ["confirmed", "deaths", "recovered"]

def make_global_df():
    def make_df(condition):
        df = pd.read_csv(f"data/time_{condition}.csv")
        df = df.drop(["Province/State", "Country/Region", "Lat", "Long"], axis=1).sum().reset_index(name=condition)
        df = df.rename(columns={"index": "date"})
        return df
    final_df = None
    for condition in conditions:
        condition_df = make_df(condition)
        if final_df is None:
            final_df = condition_df
        else:
            final_df = final_df.merge(condition_df)
    return final_df

        date  confirmed   deaths  recovered
0    1/22/20          0        0          0
1    1/23/20          0        0          0
2    1/24/20          0        0          0
3    1/25/20          0        0          0
4    1/26/20          0        0          0
..       ...        ...      ...        ...
469   5/5/21    2591609  2591609    2591609
470   5/6/21    2610018  2610018    2610018
471   5/7/21    2627094  2627094    2627094
472   5/8/21    2640670  2640670    2640670
473   5/9/21    2654811  2654811    2654811

[474 rows x 4 columns]